a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
print("Sum is", a + b)
print("Difference is", a - b)
print("Product is", a * b)
print("Quotient is", a / b)
print("Remainder is", a % b)